spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_store
    username: postgres
    password: postgres
  ai:
    openai:
      api-key: ${SPRING_AI_OPENAI_API_KEY}
      embedding-api-key: ${SPRING_AI_OPENAI_API_KEY}
      embedding:
        options:
          model: text-embedding-ada-002
      base-url: https://api.openai.com/
      chat:
        options:
          temperature: 0.2
          model: gpt-3.5-turbo
