#Local environment set up - using Postgres vector database and Azure Open AI

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vector_store
    username: postgres
    password: postgres
    ###################
    # Azure Open AI specific properties
    ###################
  ai:
    azure:
      openai:
        api-key: ${SPRING_AI_AZURE_OPENAI_API_KEY}
        endpoint: ${SPRING_AI_AZURE_OPENAI_ENDPOINT}
        chat:
          options:
            deployment-name: azure-rag-poc
        embedding:
          options:
            deployment-name: text-embedding-ada-002